# Generated by Django 4.2.7 on 2023-11-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('input_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('selection', models.CharField(blank=True, choices=[('option1', 'Great Barrier Reef'), ('option2', 'Whitsundays'), ('option3', "K'gari (Fraser Island)")], max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='contact_form',
        ),
    ]
