# Generated by Django 4.2.7 on 2023-11-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_us_delete_contact_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='selection',
            field=models.IntegerField(choices=[('option1', 'Great Barrier Reef'), ('option2', 'Whitsundays'), ('option3', 'Kgari (Fraser Island)')], default=1),
        ),
    ]
