# Generated by Django 4.2.7 on 2023-11-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_us_selection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='contactForm',
        ),
    ]
