# Generated by Django 3.2.23 on 2023-11-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regions',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='regions',
            new_name='region',
        ),
    ]
